---
services:
  app:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./config:/config
      - /mnt/public/Videos/TV Shows:/tv 
      - /mnt/tyler/videos/MakeMKV:/makemkv 
    ports:
      - 8989:8989


networks:
  default:
    driver: overlay
    name: sonarr
